version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - MONGO_USER=dbadmin
      - MONGO_PASSWORD=dbadminpassword
      - JWT_SECRET=jwtjwtsecretsecret
      - MASTER_SECRET=mastermastersecretsecret
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev